# Generated by Django 5.1.2 on 2024-10-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagess',
            field=models.ImageField(default='media/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=6),
        ),
    ]
