# Generated by Django 5.1.2 on 2024-11-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='documents_proof',
            field=models.FileField(default='path/to/default/file.pdf', upload_to='proofs/'),
        ),
    ]
