# Generated by Django 5.1.2 on 2024-11-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_request_documents_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='documents_proof',
        ),
        migrations.AddField(
            model_name='request',
            name='proofs',
            field=models.FileField(default='path/to/default/file.pdf', upload_to='proofs/'),
        ),
    ]
